/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/bookmarks': RouteRecordInfo<'/bookmarks', '/bookmarks', Record<never, never>, Record<never, never>>,
    '/notes': RouteRecordInfo<'/notes', '/notes', Record<never, never>, Record<never, never>>,
    '/posts/': RouteRecordInfo<'/posts/', '/posts', Record<never, never>, Record<never, never>>,
    '/posts/a-discussion-about-oj-of-ed-discussion': RouteRecordInfo<'/posts/a-discussion-about-oj-of-ed-discussion', '/posts/a-discussion-about-oj-of-ed-discussion', Record<never, never>, Record<never, never>>,
    '/posts/a-discussion-about-oj-of-ed-discussion-zh': RouteRecordInfo<'/posts/a-discussion-about-oj-of-ed-discussion-zh', '/posts/a-discussion-about-oj-of-ed-discussion-zh', Record<never, never>, Record<never, never>>,
    '/posts/about-principles-of-compiling-1': RouteRecordInfo<'/posts/about-principles-of-compiling-1', '/posts/about-principles-of-compiling-1', Record<never, never>, Record<never, never>>,
    '/posts/adding-wakatime-page': RouteRecordInfo<'/posts/adding-wakatime-page', '/posts/adding-wakatime-page', Record<never, never>, Record<never, never>>,
    '/posts/ai-works-for-you': RouteRecordInfo<'/posts/ai-works-for-you', '/posts/ai-works-for-you', Record<never, never>, Record<never, never>>,
    '/posts/diving-into-code': RouteRecordInfo<'/posts/diving-into-code', '/posts/diving-into-code', Record<never, never>, Record<never, never>>,
    '/posts/do-not-install-macos-in-external-disk': RouteRecordInfo<'/posts/do-not-install-macos-in-external-disk', '/posts/do-not-install-macos-in-external-disk', Record<never, never>, Record<never, never>>,
    '/posts/how-i-manage-environment-versions': RouteRecordInfo<'/posts/how-i-manage-environment-versions', '/posts/how-i-manage-environment-versions', Record<never, never>, Record<never, never>>,
    '/posts/lanqiao-2022-1': RouteRecordInfo<'/posts/lanqiao-2022-1', '/posts/lanqiao-2022-1', Record<never, never>, Record<never, never>>,
    '/posts/lanqiao-2022-2': RouteRecordInfo<'/posts/lanqiao-2022-2', '/posts/lanqiao-2022-2', Record<never, never>, Record<never, never>>,
    '/posts/lanqiao-2022-3': RouteRecordInfo<'/posts/lanqiao-2022-3', '/posts/lanqiao-2022-3', Record<never, never>, Record<never, never>>,
    '/posts/lanqiao-2023-1': RouteRecordInfo<'/posts/lanqiao-2023-1', '/posts/lanqiao-2023-1', Record<never, never>, Record<never, never>>,
    '/posts/lanqiao-2023-2': RouteRecordInfo<'/posts/lanqiao-2023-2', '/posts/lanqiao-2023-2', Record<never, never>, Record<never, never>>,
    '/posts/lanqiao-2023-3': RouteRecordInfo<'/posts/lanqiao-2023-3', '/posts/lanqiao-2023-3', Record<never, never>, Record<never, never>>,
    '/posts/lanqiao-2024-1': RouteRecordInfo<'/posts/lanqiao-2024-1', '/posts/lanqiao-2024-1', Record<never, never>, Record<never, never>>,
    '/posts/lanqiao-2024-2': RouteRecordInfo<'/posts/lanqiao-2024-2', '/posts/lanqiao-2024-2', Record<never, never>, Record<never, never>>,
    '/posts/lanqiao-2024-3': RouteRecordInfo<'/posts/lanqiao-2024-3', '/posts/lanqiao-2024-3', Record<never, never>, Record<never, never>>,
    '/posts/my-git-workflow': RouteRecordInfo<'/posts/my-git-workflow', '/posts/my-git-workflow', Record<never, never>, Record<never, never>>,
    '/posts/my-git-workflow-2': RouteRecordInfo<'/posts/my-git-workflow-2', '/posts/my-git-workflow-2', Record<never, never>, Record<never, never>>,
    '/posts/nushell-introduce': RouteRecordInfo<'/posts/nushell-introduce', '/posts/nushell-introduce', Record<never, never>, Record<never, never>>,
    '/posts/os-01-fd': RouteRecordInfo<'/posts/os-01-fd', '/posts/os-01-fd', Record<never, never>, Record<never, never>>,
    '/posts/smarter-clone': RouteRecordInfo<'/posts/smarter-clone', '/posts/smarter-clone', Record<never, never>, Record<never, never>>,
    '/posts/vue-computed-model': RouteRecordInfo<'/posts/vue-computed-model', '/posts/vue-computed-model', Record<never, never>, Record<never, never>>,
    '/projects': RouteRecordInfo<'/projects', '/projects', Record<never, never>, Record<never, never>>,
    '/videos': RouteRecordInfo<'/videos', '/videos', Record<never, never>, Record<never, never>>,
  }
}
